// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCore.Models;

[Table("Grade")]
public partial class Grade
{
    [Key]
    public int GradeId { get; set; }

    [StringLength(30)]
    public string GradeName { get; set; }

    [StringLength(50)]
    public string Section { get; set; }

    [InverseProperty("CurrentGrade")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}